/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

// Emoji were removed from these labels in the Phase 1 design pass, for the same
// reason they were removed from the homepage cards: they render differently on
// every OS and read as unfinished. Section iconography returns in Phase 2 as
// inline SVG, via a wrapped DocSidebarItem swizzle.
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/create-account',
        'getting-started/fund-account',
        'getting-started/security-setup',
        'getting-started/platform-overview',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Trading',
      collapsed: false,
      items: [
        'trading/metastation-account',
        'trading/connect-exchange',
        'trading/spot-trading',
        'trading/futures-trading',
        'trading/advanced-orders',
        'trading/account-slots',
        'trading/order-types-reference',
      ],
    },
    {
      type: 'category',
      label: 'Social Trading',
      collapsed: true,
      items: [
        'social-trading/browse-marketplace',
        'social-trading/subscribe-provider',
        'social-trading/copy-settings',
        'social-trading/become-provider',
      ],
    },
    {
      type: 'category',
      label: 'Automation',
      collapsed: true,
      items: [
        'automation/webhook-trading',
        'automation/tradingview-setup',
        'automation/telegram-to-trade',
      ],
    },
    {
      type: 'category',
      label: 'Wallet',
      collapsed: true,
      items: [
        'wallet/deposit',
        'wallet/withdraw',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        'security/two-factor-auth',
        'security/withdrawal-whitelist',
        'security/api-key-management',
        'security/session-management',
      ],
    },
    {
      type: 'category',
      label: 'Developer Reference',
      collapsed: true,
      items: [
        'developer/webhook-api-overview',
        'developer/json-format',
        'developer/natural-language-format',
        'developer/supported-actions',
        'developer/tradingview-templates',
        'developer/error-codes',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      link: {
        type: 'doc',
        id: 'api/metastation-webhook-api',
      },
      // Autogenerated on purpose, rather than importing docs/api/sidebar.ts.
      //
      // docusaurus-plugin-openapi-docs emits that sidebar as TypeScript, and
      // this file is CommonJS — a require() of a .ts module fails without a TS
      // loader in the chain. Autogeneration reads the same front matter the
      // generator writes (sidebar_label, sidebar_position, and the
      // sidebar_class_name that paints the method badge), so the result is
      // equivalent and it stays correct when the spec grows new paths.
      //
      // Regenerate with: npx docusaurus gen-api-docs all
      // Clean with:      npx docusaurus clean-api-docs all
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

module.exports = sidebars;
