import React from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import shots from '@site/src/data/screenshots.json';
import styles from './styles.module.css';

/**
 * A captured platform screenshot.
 *
 *   <Screenshot id="webhook-urls" />
 *
 * Registered globally in src/theme/MDXComponents.js, so docs use it without an
 * import. Data comes from src/data/screenshots.json, generated by
 * scripts/screens-wire.mjs off the capture manifests - the docs never hardcode
 * a path or a dimension.
 *
 * Two things this deliberately does:
 *
 *  - Emits explicit width and height. Without them every image costs layout
 *    shift, and CLS is already at 0.102 against a 0.1 budget on this site.
 *
 *  - Serves the 390px capture to narrow viewports through <picture>. The
 *    desktop capture of a trading terminal is unreadable scaled into a phone
 *    column, which makes it worse than no image.
 */
export default function Screenshot({ id, alt, caption, className }) {
  const { siteConfig } = useDocusaurusContext();
  const entry = shots[id];

  // Captures are hosted on MetaStation-fi/brand-assets and served by jsDelivr,
  // tag-pinned, so this origin serves no images at all. customFields.screensCdn
  // carries the tagged prefix; bumping to a new docs-v* tag is that one line.
  //
  // The fallback to a local path exists only for working on captures before
  // they are published — CI has no local copies, so a build with screensCdn
  // unset would ship broken images rather than stale ones.
  const cdn = siteConfig?.customFields?.screensCdn || '';
  const localDesktop = useBaseUrl(entry ? '/img/screens/' + entry.desktop.src : '/');
  const localMobile = useBaseUrl(entry?.mobile ? '/img/screens/' + entry.mobile.src : '/');

  if (!entry) {
    // A missing id is an authoring error, not a runtime one. Say so in
    // development and render nothing in production rather than shipping a
    // broken image box.
    if (process.env.NODE_ENV !== 'production') {
      return (
        <div className={styles.missing}>
          Unknown screenshot id: <code>{id}</code>
        </div>
      );
    }
    return null;
  }

  const src = cdn ? cdn + '/' + entry.desktop.src : localDesktop;
  const mobileSrc = entry.mobile ? (cdn ? cdn + '/' + entry.mobile.src : localMobile) : null;
  const text = alt || entry.alt || id;

  return (
    <figure className={className ? `${styles.figure} ${className}` : styles.figure}>
      <picture>
        {mobileSrc && (
          <source
            media="(max-width: 700px)"
            srcSet={mobileSrc}
            width={entry.mobile.width}
            height={entry.mobile.height}
          />
        )}
        <img
          className={styles.img}
          src={src}
          width={entry.desktop.width}
          height={entry.desktop.height}
          alt={text}
          loading="lazy"
          decoding="async"
        />
      </picture>
      {caption ? <figcaption className={styles.caption}>{caption}</figcaption> : null}
    </figure>
  );
}
